#!/bin/sh

INSTALL="$(pwd)/ext/"
GLFW_URL="https://github.com/glfw/glfw/releases/download/3.3.2/glfw-3.3.2.zip"
FONT_URL="https://github.com/acgaudette/kufont-ascii.git"
HEAD_URL="https://github.com/acgaudette/acg.git"
 ALG_URL="https://github.com/acgaudette/alg.git"

mkdir -p assets && cd assets

! test -d kufont* && git clone $FONT_URL
! test -f font.pbm \
    && ln -s kufont*/*.pbm font.pbm
cd ..

mkdir -p ext && cd ext

mkdir -p include && cd include
! test -d acg && git clone $HEAD_URL
! test -d alg && git clone  $ALG_URL
cd ..

mkdir -p src && cd src
! test -f glfw*.zip && wget $GLFW_URL
! test -d glfw*/ && unzip glfw*.zip

cd glfw*/ && cmake              \
    -DBUILD_SHARED_LIBS=OFF .   \
    -DGLFW_VULKAN_STATIC=OFF .  \
    -DGLFW_BUILD_EXAMPLES=OFF . \
    -DGLFW_BUILD_DOCS=OFF .     \
    -DCMAKE_INSTALL_PREFIX=$INSTALL

make -j$(expr $(nproc) + 1) \
    && make install
