#!/bin/sh

mkdir -p bin && \
clang -O0 -ggdb main.c \
-fPIC \
-DDEBUG -DALG_DEBUG \
-DINP_TEXT \
-I lib/glfw*/include \
-L lib/glfw*/src \
-lglfw -lvulkan \
-ldl -lX11 -lm -lpthread \
-shared -o bin/libtxtquad.so

# TODO: avoid linking against system glfw.so
